PMS/PMS/Models/PMSModel/Owner.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models.PMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Owner()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string OwnerName { get; set; }
        public string OwnerAddress { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}

PMS/PMS/Controllers/OwnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PMS.Models.PMSModel;
using PMS.Models.Repository;

namespace PMS.Controllers
{
    public class OwnerController : Controller
    {
        // GET: Owner
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Create(string name, string address, string number, bool isActive=false)
        {
            Owner owner = new Owner()
            {
                OwnerName = name,
                OwnerAddress = address,
                PhoneNumber = number,
                IsActive = isActive
            };
            OwnerRepository repository=new OwnerRepository();
            bool status = repository.AddOwner(owner);
           return Json(status);
        }

        public ActionResult _Index()
        {
            OwnerRepository repository = new OwnerRepository();
            var allOwners = repository.GetAllOwners();
            return  PartialView("_Index",allOwners);
        }
    }
}

PMS/PMS/Views/Owner/Index.cshtml
@{
    ViewBag.Title = "Index";
    // string test = "test";
}
<form style="margin-top: 30px">
    <input type="text" class="text_box" placeholder="owner name here.." id="ownername" />
    <input type="text" class="text_box" placeholder="owner address here.." id="owneraddress" />
    <input type="text" class="text_box" placeholder="phone number here.." id="phonenumber" />
    <label class="text_box">Is Active</label> <input type="checkbox" id="isactive" />
    <input type="button" class="btn btn-primary" value="submit" onclick="submitData()">

</form>

<div id="ownerList">

</div>
@section Scripts {
    <script>
        $(document).ready(function() {
            // console.log("Fetching..");
            getAllOwners();
        });
        var submitData = function() {
            var name = $('#ownername').val();
            var address = $('#owneraddress').val();
            var phone = $('#phonenumber').val();
            var isactive = $('#isactive').is(":checked");
            $.ajax({
                type: 'post',
                url: '@Url.Action("Create", "Owner")', //"~/owner/create"
                data: { name: name, address: address, number: phone, isActive: isactive },
                contenttype: 'json',
                datatype: 'html',
                success: function(response) {
                    if (response === true) {
                        getAllOwners();
                        alert("Data inserted successfully");
                    } else
                        alert('not inserted');
                },
                error: function() {
                    alert('errror inserting data');
                }
            });
        }
        var getAllOwners = function() {
            $.ajax({
                type: 'get',
                url: '@Url.Action("_Index", "Owner")', //"~/owner/create"
                datatype: 'html',
                success: function(response) {
                    //console.log("writing response..");
                    $("#ownerList").html(response);
                },
                error: function() {
                    alert('errror fetching data');
                }
            });
        }

        function check() {
            $.ajax({
            type: 'get',
                url: '@Url.Action("Create", "Owner")', //"~/owner/create"
                data: { name: name, address: address, number: phone, isActive: isactive },
            contenttype: 'json',
                datatype: 'html',
                success: function(response) {
                if (response === true) {
                    getAllOwners();
                    alert("Data inserted successfully");
                } else
                    alert('not inserted');
            },
            error: function() {
                alert('errror inserting data');
            }
        }
    </script>
}
    <style>
        .text_box {
            margin-left: 10px;
        }
    </style>

PMS/PMS/Views/Owner/_Index.cshtml
@model IEnumerable<PMS.Models.PMSModel.Owner>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OwnerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OwnerAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.OwnerName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OwnerAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsActive)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>